from pymongo.mongo_client import MongoClient
from pymongo.server_api import ServerApi
import random
from datetime import date, datetime
from tqdm import tqdm
import pandas as pd

uri = "mongodb://localhost:27017"
client = MongoClient(uri, server_api=ServerApi('1'))
db = client['vendas']
coluna = db['vendas']

lista_produtos = ['Sabonete líquido',
'Shampoo',
'Condicionador',
'Desodorante roll-on',
'Creme dental',
'Sabão em pó',
'Amaciante de roupas',
'Água sanitária',
'Detergente líquido',
'Papel higiênico',
'Guardanapos de papel',
'Fósforos',
'Pilhas AA',
'Pilhas AAA',
'Lâmpadas',
'Esponja de limpeza',
'Pano de limpeza',
'Álcool etílico',
'Óleo de soja',
'Azeite de oliva',
'Vinagre',
'Sal refinado',
'Açúcar refinado',
'Café em pó',
'Chá de camomila',
'Leite em pó',
'Leite condensado',
'Creme de leite',
'Margarina',
'Manteiga',
'Queijo ralado',
'Arroz branco',
'Feijão preto',
'Feijão carioca',
'Macarrão espaguete',
'Molho de tomate',
'Maionese',
'Ketchup',
'Mostarda',
'Sardinha em conserva',
'Atum em conserva',
'Ervilha em conserva',
'Milho em conserva',
'Geleia de frutas',
'Gelatina',
'Leite de coco',
'Creme de amendoim',
'Farinha de trigo',
'Fermento em pó',
'Geléia real',
'Açaí em pó',
'Suplemento vitamínico',
'Sabonete em barra',
'Creme hidratante para o corpo',
'Protetor solar',
'Repelente de insetos',
'Antiácido',
'Analgésico',
'Anti-inflamatório',
'Antialérgico',
'Antitussígeno',
'Antidiarreico',
'Antifúngico',
'Anti-histamínico',
'Vitamina C',
'Vitamina D',
'Vitamina E',
'Multivitamínico',
'Complexo B',
'Óleo de peixe',
'Óleo de fígado de bacalhau',
'Aspirina',
'Paracetamol',
'Ibuprofeno',
'Ácido acetilsalicílico',
'Cápsulas de alho',
'Cápsulas de ginkgo biloba',
'Cápsulas de ginseng',
'Cápsulas de óleo de fígado de bacalhau',
'Cápsulas de óleo de peixe',
'Cápsulas de vitamina C',
'Cápsulas de vitamina D',
'Cápsulas de vitamina E',
'Cápsulas de complexo B',
'Cápsulas de zinco',
'Cápsulas de magnésio',
'Cápsulas de cálcio',
'Cápsulas de ferro',
'Cápsulas de ácido fólico',
'Cápsulas de vitamina B12',
'Água mineral',
'Refrigerante',
'Suco de frutas em caixinha',
'Chá preto em sachê',
'Pipoca para micro-ondas',
'Salgadinho de milho',
'Biscoito recheado',
'Chocolate em barra',
'Barra de cereais',
'Sorvete de massa',
]

lista_nomes = [
'Sarah Teixeira',
'Alexandre Barbosa',
'Dra. Lara Moraes',
'Vitória Silveira',
'Luiz Fernando Teixeira',
'Juan Viana',
'Theo Nunes',
'Dr. Enzo Porto',
'Kevin Gomes',
'Kaique Rodrigues',
'Luiz Felipe Barros',
'Lucca Dias',
'Clarice Mendes',
'Alexandre da Mota',
'Marcela Moura',
'Danilo Rodrigues',
'Stephany Rodrigues',
'Luna Novaes',
'João Lucas Teixeira',
'Diego Rocha',
'Enrico Aragão',
'Vitor Rezende',
'Heloísa da Cunha',
'Dra. Maria Clara Teixeira',
'Gabrielly Ribeiro',
'Bruno Peixoto',
'Lorena Novaes',
'Yasmin Rodrigues',
'Enrico Cardoso',
'Maria Vitória Silveira',
'Nathan Melo',
'Luiz Otávio Pereira',
'Dra. Maria Clara Cavalcanti',
'Ana Lívia Farias',
'Luiza Souza',
'Maria Clara Martins',
'Cecília Oliveira',
'Luiz Otávio Correia',
'Clarice Cunha',
'Lara Castro',
'Bianca Moraes',
'Paulo da Cunha',
'Stephany Jesus',
'Isabella Pereira',
'Mariane da Costa',
'Diogo Melo',
'Pietro Farias',
'Melissa Viana',
'Dra. Larissa Azevedo',
'Brenda da Costa',
'Sra. Maria Vitória Duarte',
'Emilly Moraes',
'Marcos Vinicius Silveira',
'Elisa Ribeiro',
'Gabriel Pires',
'Gabrielly da Costa',
'Nathan Nogueira',
'Heitor Moraes',
'Leandro Oliveira',
'Igor da Rosa',
'Sr. Pietro Castro',
'Juliana Melo',
'Dr. Benjamin Almeida',
'Fernando da Rocha',
'Dra. Kamilly Lima',
'Dr. Luiz Gustavo Alves',
'Sra. Ana Carolina Farias',
'Srta. Evelyn Teixeira',
'Laís Ferreira',
'Dra. Daniela da Paz',
'Maria Julia Jesus',
'Cauê Azevedo',
'Lavínia da Rocha',
'Srta. Juliana da Luz',
'Otávio Costela',
'Srta. Maria Luiza das Neves',
'Isabel Costa',
'Henrique da Costa',
'Bianca Pinto',
'Heitor da Conceição',
'Rodrigo Mendes',
'Kaique Silveira',
'Maria Clara Carvalho',
'Maria Sophia Correia',
'Thales Rocha',
'Helena Barros',
'Rafael Azevedo',
'Davi Lucca Campos',
'Nina Lopes',
'Sabrina Farias',
'Vicente Campos',
'Isabella da Rocha',
'Dr. Cauã Jesus',
'Brenda Pires',
'João Felipe Costela',
'Sra. Giovanna Santos',
'Dra. Laura Teixeira',
'Dr. Joaquim Fogaça',
'Arthur Moraes',
'Caroline Aragão',
'Alice Vieira',
'Guilherme Ramos',
'Emanuelly Lima',
'Sr. Leonardo Azevedo',
'Letícia Jesus',
'Milena da Paz',
'Caio Mendes',
'Eloah Moraes',
'Pedro Miguel Araújo',
'Lorenzo Silva',
'Brenda Rocha',
'Cauê Lima',
'Dr. João Vitor Pires',
'Cecília Fernandes',
'Amanda Pereira',
'Pedro Lucas Pinto',
'João Pedro Monteiro',
'Antônio Souza',
'Maria Vitória Costela',
'Julia Aragão',
'João Gabriel da Rosa',
'Thales Lopes',
'Larissa Gonçalves',
'Valentina Vieira',
'João Gabriel Alves',
'Heloísa Peixoto',
'João Vitor Mendes',
'Marina Lopes',
'Rebeca Castro',
'Vitor da Cunha',
'Dr. Matheus Correia',
'Noah Peixoto',
'Noah Almeida',
'Benjamin Gonçalves',
'Pedro Miguel Moura',
'Kevin Silveira',
'Ana Almeida',
'Caio das Neves',
'Sr. Vitor Fogaça',
'Bruna Santos',
'Eloah Cardoso',
'Evelyn Ferreira',
'Bernardo Silveira',
'Srta. Letícia Gonçalves',
'Vitor Hugo Vieira',
'Murilo das Neves',
'Eduarda Moura',
'Maria Sophia Castro',
'Levi Duarte',
'Sra. Ana Laura Costela',
]

lista_categoria = [
'Bebidas alcoólicas',
'Bebidas não alcoólicas',
'Carne bovina',
'Carne suína',
'Frango',
'Peixes e frutos do mar',
'Leite e laticínios',
'Ovos',
'Pães e produtos de padaria',
'Cereais e grãos',
'Arroz',
'Massas',
'Óleos e gorduras',
'Açúcar e adoçantes',
'Chocolates e doces',
'Produtos enlatados',
'Produtos congelados',
'Produtos orgânicos',
'Produtos naturais',
'Produtos sem glúten',
'Produtos sem lactose',
'Produtos veganos',
'Produtos vegetarianos',
'Carnes processadas',
'Produtos diet',
'Produtos light',
'Refrigerantes',
'Água mineral',
'Chás',
'Cafés',
'Cervejas',
'Vinhos',
'Espumantes',
'Sucos naturais',
'Sucos em pó',
'Achocolatados',
'Refrigerantes diet',
'Refrigerantes light',
'Refrigerantes zero açúcar',
'Água com gás',
'Água saborizada',
'Leite condensado',
'Creme de leite',
'Iogurtes',
'Queijos',
'Manteiga',
'Margarina',
'Geléias e compotas',
'Mel',
'Pão de queijo',
'Pão francês',
'Pão integral',
'Biscoitos',
'Bolachas',
'Salgadinhos',
'Snacks',
'Barras de cereal',
'Granola',
'Farinha de trigo',
'Farinha de mandioca',
'Farinha de milho',
'Farinha de arroz',
'Farinha de aveia',
'Farinha de linhaça',
'Feijão',
'Lentilha',
'Grão-de-bico',
'Soja',
'Amendoim',
'Castanhas e nozes',
'Passas',
'Frutas secas',
'Arroz integral',
'Macarrão integral',
'Pão integral',
'Granola integral',
'Mel integral',
'Chá verde',
'Chá de camomila',
'Chá de hortelã',
'Chá de erva-doce',
'Café solúvel',
'Café gourmet',
'Cerveja artesanal',
'Vinho tinto',
'Vinho branco',
'Vinho rosé',
'Suco detox',
'Suco de laranja',
'Suco de uva',
'Suco de maracujá',
'Suco de limão',
'Leite de soja',
'Leite de amêndoas',
'Leite de aveia',
'Leite de coco',
'Cream cheese',
'Ricota',
'Cottage',
'Requeijão',
]

lista_marca = [
'Taeq',
'Qualitá',
'Dia',
'Carrefour Discount',
'Sabor de Casa',
'Armazém do Grão',
'Compre Bem',
'Oba',
'Primor',
'Qualimais',
'Giroil',
'Kimimo',
'Nutripleno',
'Cereal Mix',
'Cuida Bem',
'Delícias da Fazenda',
'Nutrigood',
'Vitalin',
'Casa Fiesta',
'Ecochef',
'Econômico',
'Sodishop',
'Tio João',
'União',
'Bela Vista',
'Campo Largo',
'Cereser',
'Chinezinho',
'Colombo',
'Cotochés',
'Cristal',
'Frangão',
'Guaracamp',
'Itambézinho',
'Jussara',
'Kero',
'LeitBom',
'Lucrecia',
'Magnata',
'Massa Leve',
'Mistura Fina',
'Nova Safra',
'Novo Tempo',
'Panela Velha',
'Parati',
'Piá',
'Piracanjuba',
'Qualiclean',
'Qualimais',
'Uniagro',
]

data_aleatoria = pd.date_range(start="2000-01-01",end=datetime.today()).to_list()

for _ in tqdm(range(1_000_000)):
    dicio = {
            'cod_venda' : random.randint(1,5000),
            'data_teste': str(random.choice(data_aleatoria)),
            'cod_cliente' : random.randint(1,5000),
            'nome_cliente': random.choice(lista_nomes), 
            'cod_produto': random.randint(1,5000),
            'descricao' : random.choice(lista_produtos),
            'nome_produto': random.choice(lista_produtos),
            'categoria': random.choice(lista_categoria),
            'marca' : random.choice(lista_marca),
            'valor': round(random.uniform(1, 150),2),
            'qtd' : random.randint(1,11)
            }
    a = coluna.insert_one(dicio)
